### ISSUE TITLE
[BUG REPORT] Ability to Add Data with Fewer Dimensions than Schema in Variable Sized Dataset

### ISSUE THREAD

**Issue by rlizzo** [tensorwerk/hangar-py#109]
**Describe the bug**

ability to add arrays with fewer dimensions (and not just smaller dimension sizes) to an `arrayset` with `variable_size=True` schema. 

Though the current implementation does not support this, it won't allow records to be added in this fashion, instead forcing a ValueErrorto be raised - basically, it's a bug, but one we  have addressed by stoping execution which violates the limitations of the slice generator.

**Severity**

Select an option:
- [ ] Data Corruption / Loss of Any Kind
- [x] Unexpected Behavior, Exceptions or Error Thrown
- [ ] Performance Bottleneck

**To Reproduce**
Steps to reproduce the behavior, minimal example code preferred:

```python
>>> co = repo.checkout(write=True)
>>> aset = co.arraysets.init_arrayset('foo', shape=(10, 10, 10), dtype=np.uint8, variable=True)
>>> arr = np.random.randn(10, 10).astype(np.uin8)
>>> aset[1] = arr
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-dc4fc55d87c3> in <module>
----> 1 aset[1] = arr

~/projects/tensorwerk/hangar/hangar-py/src/hangar/arrayset.py in __setitem__(self, key, value)
    484             sample name of the stored data (assuming operation was successful)
    485         """
--> 486         self.add(value, key)
    487         return key
    488 

~/projects/tensorwerk/hangar/hangar-py/src/hangar/arrayset.py in add(self, data, name, **kwargs)
    588 
    589         except ValueError as e:
--> 590             raise e from None
    591 
    592         # --------------------- add data to storage backend -------------------

~/projects/tensorwerk/hangar/hangar-py/src/hangar/arrayset.py in add(self, data, name, **kwargs)
    576                 if data.ndim != len(self._schema_max_shape):
    577                     raise ValueError(
--> 578                         f'`data` rank: {data.ndim} != aset rank: {len(self._schema_max_shape)}')
    579                 for dDimSize, schDimSize in zip(data.shape, self._schema_max_shape):
    580                     if dDimSize > schDimSize:

ValueError: `data` rank: 2 != aset rank: 3
```

**Expected behavior**

```python
>>> aset[1] = arr
>>> out = aset[1]
>>> out.shape
(10, 10)
```

**Comment by elistevens** [comment]
This doesn't seem like a bug to me.  I can add an `.unsqueeze(0)` call if needed.

**Comment by rlizzo** [comment]
Upon further discussion with @elistevens we decided this was not a bug and would remain as a restriction for the time being. In the end this is one less check that a user has to do when reading or writing data.
