### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by rgalbo** [tensorwerk/hangar-py#119]
**Describe the bug**

current pip install is missing google requirement. `import hangar` fails because `google` is missing

**Severity**

Select an option:
- [ ] Data Corruption / Loss of Any Kind
- [ ] Unexpected Behavior, Exceptions or Error Thrown
- [ ] Performance Bottleneck

**To Reproduce**
Steps to reproduce the behavior, minimal example code preferred:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS:
 - Python:
 - Hangar:

**Additional context**

**Comment by rlizzo** [comment]
Hey @rgalbo, Thanks for the bug report! I don't know how, but we missed the `protobuf` dependency in the pip package. Will fix this ASAP!

**Comment by rlizzo** [comment]
for a quick fix, just `pip install protobuf` and you should be good

**Comment by rgalbo** [comment]
should this issue be closed? i see that `protobuf` has now been added to `setup.py`

**Comment by rlizzo** [comment]
Closed with release 0.3. Thanks for the help!!
