### ISSUE TITLE
Support Tensorflow 2.0 Release

### ISSUE THREAD

**Issue by rlizzo** [tensorwerk/hangar-py#126]
@hhsecond, Tensorflow 2.0 has been released. https://www.tensorflow.org/install

Are there any changes which will prevent us from supporting both 1.14 as well as 2.0?

**Comment by hhsecond** [comment]
Ideally No. I had verified our APIs with the experimental 2.0 already. But let's keep this issue open till I do proper verification now since 2.0 is out officially

**Comment by rlizzo** [comment]
Ok. I'm gonna mark this as a potential bug until we get it figured out then. Let me know when you have more info.

**Comment by hhsecond** [comment]
@rlizzo Verified that I could create and consume tf dataset with `make_tf_dataset` using TF 2.0. However,  GPU is getting exhausted pretty soon (apparently we had this issue in tf1.14 as well). I am going to verify this in colab and will create another issue for that.
