### ISSUE TITLE
[FEATURE REQUEST] More options through command line interface

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#132]
**Is your feature request related to a problem? Please describe.**
We need more options in our CLI for making few workflows seamless. Two examples I could think off
1. create dataset: We have repo init and data import through CLI but without the option to create a dataset through CLI, the user will always have to go through python APIs
2. commit: Now, if users import data using `hangar import`, they will need to spin up a python program and use the python APIs to commit the staged data

**Comment by rlizzo** [comment]
I'll take this. Will be done in the next week or ao
