### ISSUE TITLE
[BUG REPORT] Setup.py installation failing

### ISSUE THREAD

**Issue by jicksonp** [tensorwerk/hangar-py#136]
`python setup.py develop` command failed with below error message.

> 
> Best match: blosc 1.8.1
> Processing blosc-1.8.1.tar.gz
> Writing /var/folders/yl/9l3dn2s53wdd4__5v1p1cwbm0000gn/T/easy_install-b7znieg5/blosc-1.8.1/setup.cfg
> Running blosc-1.8.1/setup.py -q bdist_egg --dist-dir /var/folders/yl/9l3dn2s53wdd4__5v1p1cwbm0000gn/T/easy_install-b7znieg5/blosc-1.8.1/egg-dist-tmp-6xli48d_
> SSE2 detected
> warning: no files found matching '*.hpp' under directory 'c-blosc'
> c-blosc/internal-complibs/zlib-1.2.8/gzread.c:30:15: warning: implicit declaration of function 'read'
>       is invalid in C99 [-Wimplicit-function-declaration]
>         ret = read(state->fd, buf + *have, len - *have);
>               ^
> c-blosc/internal-complibs/zlib-1.2.8/gzread.c:30:15: warning: this function declaration is not a
>       prototype [-Wstrict-prototypes]
> c-blosc/internal-complibs/zlib-1.2.8/gzread.c:591:11: warning: implicit declaration of function
>       'close' is invalid in C99 [-Wimplicit-function-declaration]
>     ret = close(state->fd);
>           ^
> c-blosc/internal-complibs/zlib-1.2.8/gzread.c:591:11: warning: this function declaration is not a
>       prototype [-Wstrict-prototypes]
> 4 warnings generated.
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:256:24: warning: implicit declaration of function
>       'lseek' is invalid in C99 [-Wimplicit-function-declaration]
>         state->start = LSEEK(state->fd, 0, SEEK_CUR);
>                        ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
>  #  define LSEEK lseek
>                 ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:256:24: warning: this function declaration is not a
>       prototype [-Wstrict-prototypes]
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
>  #  define LSEEK lseek
>                 ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:355:9: warning: implicit declaration of function 'lseek'
>       is invalid in C99 [-Wimplicit-function-declaration]
>     if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
>         ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
> #  define LSEEK lseek
>                 ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:396:15: warning: implicit declaration of function
>       'lseek' is invalid in C99 [-Wimplicit-function-declaration]
>         ret = LSEEK(state->fd, offset - state->x.have, SEEK_CUR);
>               ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
> #  define LSEEK lseek
>                 ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:492:14: warning: implicit declaration of function
>       'lseek' is invalid in C99 [-Wimplicit-function-declaration]
>     offset = LSEEK(state->fd, 0, SEEK_CUR);
>              ^
> c-blosc/internal-complibs/zlib-1.2.8/gzlib.c:14:17: note: expanded from macro 'LSEEK'
> #  define LSEEK lseek
>                 ^
> 5 warnings generated.
> c-blosc/internal-complibs/zlib-1.2.8/gzwrite.c:84:15: warning: implicit declaration of function
>       'write' is invalid in C99 [-Wimplicit-function-declaration]
>         got = write(state->fd, strm->next_in, strm->avail_in);
>               ^
> c-blosc/internal-complibs/zlib-1.2.8/gzwrite.c:84:15: warning: this function declaration is not a
>       prototype [-Wstrict-prototypes]
> c-blosc/internal-complibs/zlib-1.2.8/gzwrite.c:101:33: warning: implicit declaration of function
>       'write' is invalid in C99 [-Wimplicit-function-declaration]
>             if (have && ((got = write(state->fd, state->x.next, have)) < 0 ||
>                                 ^
> c-blosc/internal-complibs/zlib-1.2.8/gzwrite.c:573:9: warning: implicit declaration of function
>       'close' is invalid in C99 [-Wimplicit-function-declaration]
>     if (close(state->fd) == -1)
>         ^
> c-blosc/internal-complibs/zlib-1.2.8/gzwrite.c:573:9: warning: this function declaration is not a
>       prototype [-Wstrict-prototypes]
> 5 warnings generated.
> In file included from c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:27:
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstd_compress_internal.h:190:5: error: unknown type
>       name 'ZSTD_dictAttachPref_e'
>     ZSTD_dictAttachPref_e attachDictPref;
>     ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:675:85: error: use of undeclared
>       identifier 'ZSTD_c_forceMaxWindow'; did you mean 'ZSTD_p_forceMaxWindow'?
>   ...const forceWindowError = ZSTD_CCtxParam_setParameter(&jobParams, ZSTD_c_forceMaxWindow, !job-...
>                                                                       ^~~~~~~~~~~~~~~~~~~~~
>                                                                       ZSTD_p_forceMaxWindow
> //anaconda3/include/zstd.h:1110:5: note: 'ZSTD_p_forceMaxWindow' declared here
>     ZSTD_p_forceMaxWindow=1100, /* Force back-reference distances to remain < windowSize,
>     ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:999:21: error: use of undeclared
>       identifier 'ZSTD_OVERLAPLOG_MIN'
>         if (value < ZSTD_OVERLAPLOG_MIN) value = ZSTD_OVERLAPLOG_MIN;
>                     ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:999:50: error: use of undeclared
>       identifier 'ZSTD_OVERLAPLOG_MIN'
>         if (value < ZSTD_OVERLAPLOG_MIN) value = ZSTD_OVERLAPLOG_MIN;
>                                                  ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:1000:21: error: use of undeclared
>       identifier 'ZSTD_OVERLAPLOG_MAX'
>         if (value > ZSTD_OVERLAPLOG_MAX) value = ZSTD_OVERLAPLOG_MAX;
>                     ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:1000:50: error: use of undeclared
>       identifier 'ZSTD_OVERLAPLOG_MAX'
>         if (value > ZSTD_OVERLAPLOG_MAX) value = ZSTD_OVERLAPLOG_MAX;
>                                                  ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:1171:14: error: use of undeclared
>       identifier 'ZSTD_btultra2'; did you mean 'ZSTD_btultra'?
>         case ZSTD_btultra2:
>              ^~~~~~~~~~~~~
>              ZSTD_btultra
> //anaconda3/include/zstd.h:450:42: note: 'ZSTD_btultra' declared here
>                ZSTD_btlazy2, ZSTD_btopt, ZSTD_btultra } ZSTD_strategy;   /* from faster to st...
>                                          ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:1173:14: error: duplicate case value
>       'ZSTD_btultra'
>         case ZSTD_btultra:
>              ^
> c-blosc/internal-complibs/zstd-1.3.8/compress/zstdmt_compress.c:1171:14: note: previous case defined
>       here
>         case ZSTD_btultra2:
>              ^
> 8 errors generated.
> error: Setup script exited with error: command 'gcc' failed with exit status 1

**Desktop (please complete the following information):**

 - OS: MacOs Mojave, 10.14.6
 - Python: 3.7.3, Anaconda
 - Hangar: master branch

**Comment by rlizzo** [comment]
Hey @jicksonp. I'll take a look into this tonight. thanks for the bug report! sorry this is giving you issues!

**Comment by rlizzo** [comment]
Hey @jicksonp, thanks for the bug report. Sorry you're having issues!

I have a few potential solutions, but this is screaming of a compiler issue. I also use anaconda as my python package manager, and have also found some incompatibilities which the conda compiler while trying to build blosc. 

### Solution 1

Repull the lastest changes from the master branch, and in a new conda environment (a clean environment, just having been setup with `conda create -n foo python=3.7` try the `python setup.py develop command`. I merged some changes in #130 which removed a few dependencies. These may be all that's needed

### Solution 2:

Use the same packages we use for our distribution on `conda-forge`. We explicitly disable some compiler flags, and use the conda `python-blosc` package binary to make this work. 

From the base conda environment.

```
export CC=gcc
export CXX=g++
export INCLUDE_ZSTD=0
export DISABLE_BLOSC_SSE2=0
conda update conda
conda create -n foo -c conda-forge python=3.7 python-blosc zstd zlib
conda activate foo
python setup.py develop
```

### Solution 3

If you don't need the latest dev install (and just want to try hangar out with conda) use the precompiled binary on [`conda-forge`](https://anaconda.org/conda-forge/hangar)

```
conda create -n foo -c conda-forge python=3.7 hangar
```

### Follow up

Let me know if any of these work for you. If you encounter other errors, or are still stuck post as much info as you can about the system and the conda environment your using and I will debug with you further. 

Best,
Rick

**Comment by jicksonp** [comment]
Hi @rlizzo, **Solution 1** worked fine. Thank you 👍

**Comment by rlizzo** [comment]
👍  you are welcome!
