### ISSUE TITLE
Not able to import hangar

### ISSUE THREAD

**Issue by vhawk19** [tensorwerk/hangar-py#137]
`` import hangar ``
threw the error
`` Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/varun/hangar-py/src/hangar/__init__.py", line 5, in <module>
    from .remote.server import serve
  File "/home/varun/hangar-py/src/hangar/remote/server.py", line 18, in <module>
    from . import chunks
  File "/home/varun/hangar-py/src/hangar/remote/chunks.py", line 6, in <module>
    from . import hangar_service_pb2
  File "/home/varun/hangar-py/src/hangar/remote/hangar_service_pb2.py", line 23, in <module>
    TypeError: __new__() got an unexpected keyword argument ``

after running `` sudo python3 setup.py develop``

Python Version - 3.6.7

Environment
varun@pop-os
OS: Ubuntu 18.04 bionic (pop-os)
Kernel: x86_64 Linux 4.18.0-16-generic
Uptime: 1h 12m
Packages: 3599
Shell: bash 4.4.19
Resolution: 1920x1080
DE: KDE 5.44.0 / Plasma 5.12.7
WM: KWin
WM Theme: Breeze
GTK Theme: Breeze [GTK2/3]
Icon Theme: breeze
Font: Noto Sans Regular
CPU: Intel Core i7-8750H @ 12x 4.1GHz [57.0°C]
GPU: intel
RAM: 2968MiB / 7817MiB

Also not able to run ``hangar init`` as it resulted in 
``raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lmdb<=0.96,>=0.94' distribution was not found and is required by hangar``
after installing lmdb 0.95 it still threw the same error

**Comment by rlizzo** [comment]
Hey @vhawk19 I'll take a look at this tonight. Sorry this is giving you issues. Will report back soon!

**Comment by rlizzo** [comment]
Hey @vhawk19, thanks for the bug report, so sorry you are having issues! 

Can you repull the latest changes in master and try to build this again in a clean environment? I just made some changes in #130 which might solve some of these issues. 

Let me know if that works, if not I can debug further with you.

Best, Rick

**Comment by rlizzo** [comment]
Also, you wouldn't happen to be running this in the windows subystem for linux, would you?

**Comment by rlizzo** [comment]
closed due to inactivity.
