### ISSUE TITLE
[BUG REPORT] TypeError: 'rdcc_nbytes' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by ChandProj** [tensorwerk/hangar-py#139]
**Describe the bug**
" TypeError: 'rdcc_nbytes' is an invalid keyword argument for this function" on saving an image to Hangar repository 

**Severity**

Select an option:
- [ ] Data Corruption / Loss of Any Kind
- [  ] Unexpected Behavior, Exceptions or Error Thrown
- [ ] Performance Bottleneck

**To Reproduce**
import hangar
repo=hangar.Repository('.')
repo.init(user_name='chandnika', user_email='a@b.c')
co=repo.checkout(write=True)
import numpy as np
co.arraysets.init_arrayset('images' ,shape=(10,10,3) , dtype=np.uint8)
co.commit('arrayset init')
images=co.arraysets['images']
img=np.random.random((10,10,3)).astype(np.uint8)
images[0]=img

**Expected behavior**
TypeError                                 Traceback (most recent call last)
<ipython-input-27-29e605d9ffd5> in <module>()
----> 1 images[0]=img

5 frames
/content/hangar-py/src/hangar/arrayset.py in __setitem__(self, key, value)
    500             sample name of the stored data (assuming operation was successful)
    501         """
--> 502         self.add(value, key)
    503         return key
    504 

/content/hangar-py/src/hangar/arrayset.py in add(self, data, name, **kwargs)
    646             existingHashVal = self._hashTxn.get(hashKey, default=False)
    647             if existingHashVal is False:
--> 648                 hashVal = self._fs[self._dflt_backend].write_data(data)
    649                 self._hashTxn.put(hashKey, hashVal)
    650                 self._stageHashTxn.put(hashKey, hashVal)

/content/hangar-py/src/hangar/backends/hdf5_00.py in write_data(self, array, remote_operation)
    675                     self._create_schema(remote_operation=remote_operation)
    676         else:
--> 677             self._create_schema(remote_operation=remote_operation)
    678 
    679         srcSlc = None

/content/hangar-py/src/hangar/backends/hdf5_00.py in _create_schema(self, remote_operation)
    540                                   rdcc_nbytes=rdcc_nbytes_val,
    541                                   rdcc_w0=CHUNK_RDCC_W0,
--> 542                                   rdcc_nslots=rdcc_nslots_prime_val)
    543         self.w_uid = uid
    544         self.hNextPath = 0

/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    309             name = filename_encode(name)
    310             with phil:
--> 311                 fapl = make_fapl(driver, libver, **kwds)
    312                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    313 

/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fapl(driver, libver, **kwds)
    107             msg = "'{key}' is an invalid keyword argument for this function" \
    108                   .format(key=next(iter(kwds)))
--> 109             raise TypeError(msg)
    110         return plist
    111 

TypeError: 'rdcc_nbytes' is an invalid keyword argument for this function

**Screenshots**
![image](https://user-images.githubusercontent.com/47638190/66746768-5b923f80-eea0-11e9-9368-c464b1e96d80.png)

**Desktop (please complete the following information):**

 - OS: Google Colab Debian based Linux
 - Python: Python 3.6.8
 - Hangar: 0.3.0
 
**Additional context**

**Comment by rlizzo** [comment]
Hi @ChandProj, thanks for the bug report. Sorry you are having issues!

Thanks for the detailed bug report, but I was unable to recreate the bug as you described it (and have previously tested hangar in `colab`).

I copy/pasted the example code you provided in a `colab` project, and it runs as you can see at this link.

https://colab.research.google.com/drive/1dUYURo18UzNHp_59Fd0gYjtnadEJiAlD

Did you do anything different? Is that code able to run for you?

**Comment by ChandProj** [comment]
Hi , 
Thanks for the response.
Intsead of pip install hangar , I did git clone hangar-py.git and ran python setup.py develop 

The link to colab notebook : https://colab.research.google.com/drive/1EoGWwalUGOO4R875rKfBd67dyZPfGKiD

The link to

**Comment by ChandProj** [comment]
However, when I did pip install hangar, no issues exist.

**Comment by rlizzo** [comment]
Hey so I just tried it out, apparently google colab has an installation of `h5py` already available. However, it is `version 2.8.0` and Hangar requires `2.9.0`. If you retry your original notebook, but first `!pip install h5py==2.9.0` everything works!
