### ISSUE TITLE
[BUG REPORT] NamedTuple doesn't like all the name formats hangar allows

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#158]
**Describe the bug**
`ArraysetData` namedtuple we create on `get` throws an error if the arrayset name contains `-` or `.` or if the name starts with `_` because of the restriction namedtuple has on field names. But since hangar allows arrayset names to have these characters, we need to handle it in someway

https://github.com/tensorwerk/hangar-py/blob/b2c00161bf33118669cc7af883b5e41c86c715ff/src/hangar/checkout.py#L344
https://github.com/tensorwerk/hangar-py/blob/b2c00161bf33118669cc7af883b5e41c86c715ff/src/hangar/checkout.py#L932

**Severity**

Select an option:
- [ ] Data Corruption / Loss of Any Kind
- [x] Unexpected Behavior, Exceptions or Error Thrown
- [ ] Performance Bottleneck

**To Reproduce**
Use any of the below arrayset names
- `_startsWithUnderscore`
- `has.dot.in.between`
- `has-hyphen-in-between`

or even easier
```python
>>> from collections import namedtuple
>>> dummy = namedtuple('dummy', ['_startsWithUnderscore'])  # ValueError('Field names cannot start with an underscore: '
>>> dummy = namedtuple('dummy', ['has.dot.in.between'])  # ValueError('Type names and field names must be valid identifiers'
>>> dummy = namedtuple('dummy', ['has-hyphen-in-between'])  # ValueError('Type names and field names must be valid identifiers'
```

**Comment by rlizzo** [comment]
Ok. This is easy enough. I'll handle it in the next day orso. Thanks!
