### ISSUE TITLE
[BUG REPORT] Fetch data raises error witih default argument values

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#189]
**Describe the bug**
repo.remote.fetch_data('origin') will throw error and expect user to pass value for the optional parameters `branch` or `commit`

**Severity**

Select an option:
- [ ] Data Corruption / Loss of Any Kind
- [x] Unexpected Behavior, Exceptions or Error Thrown
- [ ] Performance Bottleneck

**To Reproduce**
```python
>>> repo = Repository(path=new_tmpdir, exists=False)
>>> repo.clone('name', 'a@b.c', server, remove_old=True)
>>> repo.remote.fetch_data('origin')
... ValueError: specified commit: None does not exist in the repo.
```

**Expected behavior**
```python
repo.remote.fetch_data('origin')
```
should fetch the commit id from the master's head.

**Comment by rlizzo** [comment]
Fixed in #208
