### ISSUE TITLE
Environment Singleton Needed?

### ISSUE THREAD

**Issue by rlizzo** [tensorwerk/hangar-py#24]
I think we should at least give the option of cleaning up the singletons (either a specific one or all of them). In general I'm not 100% sure why we need a singleton (or something like it) design-wise, can you explain in a one-liner?

_Originally posted by @lantiga in https://github.com/tensorwerk/hangar-py/pull/20#issuecomment-488382678_

**Comment by rlizzo** [comment]
From #21:

> With the bugfixes to #5 #4 in PR: #20, environment handle singletons can now potentially live indefinitly as there is no cleanup method.
> 
> Is there a way to GC the objects without introducing an explicit `.close()` method on the repository?
> 
> Tag @lantiga for discussion here.

**Comment by lantiga** [comment]
@rlizzo is your latest WIP making this one obsolete?

**Comment by rlizzo** [comment]
Yup! This will be gone as well as the HDF5 Singleton. 

Linking this to #70 for future reference.

**Comment by rlizzo** [comment]
Fixed in #70
