### ISSUE TITLE
Not catching merge conflicts

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#37]
## Expected Behavior
Hangar currently not catching merge conflicts properly. This issue keeps a track of all the test cases those expects the conflict error and could be fixed along with #32 

## Current Behavior
- [Metadata](https://github.com/tensorwerk/hangar-py/pull/27#discussion_r281062478)
- [Dataset](https://github.com/tensorwerk/hangar-py/pull/25#discussion_r281067549)

**Comment by rlizzo** [comment]
#32 should catch all relevant conflicts. test suite seems to show that it does right now.

**Comment by rlizzo** [comment]
closed from #32
