### ISSUE TITLE
Branch removal

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#38]
## Expected Behavior

```python
repo.remove_branch(branch_name)
```

## Current Behavior
NotImplemented

## Steps to Reproduce (for bugs)
https://github.com/tensorwerk/hangar-py/pull/25#discussion_r281060529

**Comment by rlizzo** [comment]
This will be for after the 0.1.0 release.

**Comment by rlizzo** [comment]
This is being pushed to the 0.3 release due to time limitations for the 0.2 release

**Comment by rlizzo** [comment]
Closed in #128
