### ISSUE TITLE
LockHeld check is failing

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#39]
## Expected Behavior
Lockheld check at diff.py should verify whether the lock is held or not
https://github.com/tensorwerk/hangar-py/blob/044937c5a00fa48bd2889cce878648404645591d/src/hangar/diff.py#L237 

## Current Behavior
Execution never reaches there

## Steps to Reproduce (for bugs)
https://github.com/tensorwerk/hangar-py/pull/25#discussion_r281060389

**Comment by rlizzo** [comment]
Good catch!

**Comment by rlizzo** [comment]
fixed in #52
