### ISSUE TITLE
[BUG REPORT] Testcases are not running for python 3.7

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#44]
**Describe the bug**
Python 3.7 test cases are not running. Yaml file only triggers docs env

**Severity**
- [ ] Data Corruption / Loss of Any Kind
- [ ] Unexpected Behavior, Exceptions or Error Thrown
- [ ] Performance Bottleneck

**Comment by rlizzo** [comment]
Is this for the appveyor/travis CI? Or for local builds? 

If for local builds, (when running with `tox`) if python 3.7 isn't available in the standard environment paths (conda is not supported) then that version of the tests wont run.

**Comment by hhsecond** [comment]
I was talking about [this](https://travis-ci.org/tensorwerk/hangar-py/jobs/533202509). It's in our configuration. Test cases are not running for 3.7 in travis

**Comment by rlizzo** [comment]
Ok. It's not a bug. That is the test to make sure the docs build. The full tests are run separately. See the jobs listed here 

https://travis-ci.org/tensorwerk/hangar-py/builds/533202508
