### ISSUE TITLE
[BUG REPORT] Test Cases Needed for New Merge/Diff Logic and API

### ISSUE THREAD

**Issue by rlizzo** [tensorwerk/hangar-py#56]
**Describe the bug**

Test cases are needed for the changes introduced in #32. 

**Severity**

Select an option:
- [ ] Data Corruption / Loss of Any Kind
- [ ] Unexpected Behavior, Exceptions or Error Thrown
- [ ] Performance Bottleneck

N/A

**To Reproduce**
Steps to reproduce the behavior, minimal example code preffered:

Run the tests

**Expected behavior**

More thorough testing.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: any
 - Python: any
 - Hangar: 0.0.0 -> 0.1 rc

**Additional context**

See #32 for changes introduced

**Comment by rlizzo** [comment]
Hi @hhsecond, can I assign this to you? I know you were starting to dig into the `diff` and `merger` internals the other day, and since this is stable (even considering the changes introduced in #70), its a good project which we won't duplicate effor on.

**Comment by hhsecond** [comment]
@rlizzo Sure, I'll take it up.

**Comment by rlizzo** [comment]
Fixed in #76
