### ISSUE TITLE
AttributeError on data removal

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#6]
While trying to remove the data with `.remove(key)`, hangar raises `AttributeError: 'DatasetDataWriter' object has no attribute 'TxnRegister'`.

**Comment by hhsecond** [comment]
It looks like a typo. Will fix it once verified.

**Comment by rlizzo** [comment]
This is definitally a typo. Good catch. The offending line is here:

https://github.com/tensorwerk/hangar-py/blob/master/src/hangar/dataset.py#L410

Instead it should be a call to `self._TxnRegister` which is defined here:

https://github.com/tensorwerk/hangar-py/blob/master/src/hangar/dataset.py#L81

**Comment by rlizzo** [comment]
Fixed in https://github.com/tensorwerk/hangar-py/pull/16
