### ISSUE TITLE
[FEATURE REQUEST] Command line options to import and export typical data file types to a dataset/checkout

### ISSUE THREAD

**Issue by rlizzo** [tensorwerk/hangar-py#72]
_Note: The feature as detailed below was initially proposed by @lantiga in an offline phone call._ 

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

In order to improve the command line experience, Hangar should provide built in tools to import common data file types stored in a directory into the staging area. In addition, in order to ease the user transition from domain-specific file formats to array based storage, a utility should be included which exports samples in a dataset into common file types. 

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Add commands to the CLI which mimic the following workflow (exact syntax and names are not super important here, just the idea of the workflow)

Importing
```
$ hangar branch --create foo
$ hangar checkout foo               # write enabled checkout which can modify the staging area
$ hangar dataset create --name images --dtype uint8 --shape 500 500 3 --variable-shape ...
$ hangar dataset import --name images --directory ~/data/images/   # directory contains image files. 
$ hangar commit -m "added data"
```

Exporting
```
$ hangar dataset export --commit foo_hash --name images --directory ~/data/images/   --format jpg
```

Notes:
- _It's important that the implementation of these utilities are not directly integrated or included into the hangar core_ (either in backend data IO processing, record reference parsing/storage/interaction, or the user facing programatic API). Instead these utilities should lie in a special module (isolated from the hangar core) where any relevant IO or data-file processing / transformation  methods are defined. This module would transform the files as necessary, and then make the standard calls into the user-facing API to interact with Hangar. 
- A few file types we could natively support would be:

  - `jpg`, `png`, `tiff`, ... (other standard image files)
  - `csv`
  - `npy` / `npz`
  - others? (open to suggestions here)

**Additional context**
_Add any other context or screenshots about the feature request here._

While the data import feature would be a very useful tool which has many uses, use of the export function as a crutch (instead of just reading data directly as arrays via the API) should not be encouraged; that type of use makes some key benefits of hangar null from the start. 

The export tool does however, have really interesting potential to provide human understandable diffs of the data which was changed between two branches or commits. I'm not quite sure how yet, as the diff interface is still really evolving, but there are interesting possibilities here. 

Tagging @rgalbo for reference in relation to the issue opened in #71

**Comment by hhsecond** [comment]
Adding my thoughts here
- We could make these installable plugins which could then be utilised by users as a template for their own import/export utilities (long shot perhaps but I think it's good to design it in this way and probably make the basic file types preinstalled)
- A bunch of audio format we could support -> mp3, wav, aac, ogg, flac, avr, cdda, cvs/vms, aiff, au, amr, mp2, mp4, ac3, avi, wmv, mpeg, ircam and any other format supported by libsox, ark/scp (copied from PyTorch audio)
- Text files perhaps with some embedding?
