### ISSUE TITLE
[FEATURE REQUEST] Accept intigers as sample name

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#86]
**Is your feature request related to a problem? Please describe.**
Sample additions become more intuitive for a beginner if we enable sample name to be integers

**Comment by rlizzo** [comment]
Totally agreed. I've been wanting to add this for a while. Ive got a design for how to do this, just haven't found the time. Now that #78 is merged its probably time.

**Comment by rlizzo** [comment]
Update  I've got this in a Dev branch I'll submit as a PR soon.
